
services:
  web:
    build: .
    container_name: sistema_mae
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: gestao
      SECRET_KEY: 3fK9!xP2@vL8#qR1$zM7nW4*YtA6bC0D

  db:
    image: mysql:8
    container_name: meu_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestao
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: